### ISSUE TITLE
I don't know how to get the settings right

### ISSUE THREAD

**Issue by Manhunter1920** [LazuriteMC/Hexaplex#1]
i get how it works but i dont know how to set it up for myself. basically i have no idea what settings are right for my colorblindness and if it helps to know, im a strong Deutan.

**Comment by The-PPWD** [comment]
If you have Hexaplex and [Mod Menu](https://www.curseforge.com/minecraft/mc-mods/modmenu) installed, you can access Hexaplex's settings screen:

![Capture](https://user-images.githubusercontent.com/47865452/113448069-c56a1600-93c0-11eb-820b-a596ca07e0a2.PNG)

If you have strong Deutan colorblindness, I'd recommend using the Deuteranomaly setting and playing with the strength and skew sliders until it looks nice to you.

Deutan was the profile I saw the least change in (in all fairness, I'm not colorblind). However, I'm going to be working on potentially updating the color profile matrices for when 1.17 releases. So try it out and let me know if it helps and/or what you'd like changed. (And thanks for using it! 😊)

**Comment by Manhunter1920** [comment]
Thanks! This Helped abunch!
